spring:

  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    servlet:
      multipart:
    file-size-threshold: 1MB
    max-file-size: 100MB
    max-request-size: 100MB

  mail:
    username: ${MAIL_USERNAME}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: ${MAIL_PASSWORD}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  main:
    allow-bean-definition-overriding: 'true'

  jwt:
    accessSecret: ${ACCESS_SECRET}
    refreshSecret: ${REFRESH_SECRET}